version: '3.9'

services:
  rest-in-a-box-django:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rest-in-a-box-django
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    working_dir: /app
